import { Dimensions, StyleSheet } from "react-native";
import { NODE_RADIUS } from "./utils/gameLogic";

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");

const GAME_WIDTH = 350;
const GAME_HEIGHT = 500;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  homeContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
  },
  logoContainer: {
    width: 120,
    height: 120,
    backgroundColor: "#3b82f6",
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 32,
    shadowColor: "#3b82f6",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  logoCircle: {
    position: "absolute",
    width: 80,
    height: 80,
    borderWidth: 4,
    borderColor: "white",
    borderRadius: 40,
  },
  title: {
    fontSize: 42,
    fontWeight: "900",
    color: "#0f172a",
    textAlign: "center",
    letterSpacing: -1,
    lineHeight: 42,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: "#94a3b8",
    fontWeight: "500",
    marginBottom: 48,
  },
  coinBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fef3c7",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginBottom: 48,
  },
  coinText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#b45309",
    marginLeft: 8,
  },
  mainButton: {
    width: "100%",
    backgroundColor: "#2563eb",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 18,
    borderRadius: 20,
    shadowColor: "#2563eb",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 5,
  },
  mainButtonText: {
    color: "white",
    fontSize: 20,
    fontWeight: "800",
    marginLeft: 12,
  },
  secondaryButtonsRow: {
    flexDirection: "row",
    marginTop: 24,
    gap: 16,
  },
  iconButton: {
    flex: 1,
    backgroundColor: "#f1f5f9",
    paddingVertical: 14,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  homeMenuGrid: {
    width: "100%",
    marginTop: 20,
    gap: 10,
  },
  homeMenuButton: {
    width: "100%",
    backgroundColor: "#e2e8f0",
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  homeMenuButtonTitle: {
    color: "#1e293b",
    fontSize: 14,
    fontWeight: "800",
  },
  levelsContainer: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: 24,
    gap: 16,
  },
  backButton: {
    width: 40,
    height: 40,
    backgroundColor: "#f1f5f9",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: "#0f172a",
  },
  levelsScroll: {
    flex: 1,
    paddingHorizontal: 24,
  },
  modeCardList: {
    flex: 1,
    paddingHorizontal: 24,
    gap: 16,
    paddingTop: 16,
  },
  modeCard: {
    backgroundColor: "white",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 20,
    gap: 12,
  },
  modeCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  modeCardTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: "#0f172a",
  },
  modeCardBody: {
    color: "#64748b",
    fontSize: 14,
    lineHeight: 20,
  },
  modeCardButton: {
    alignSelf: "flex-start",
    backgroundColor: "#2563eb",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  modeCardButtonDisabled: {
    backgroundColor: "#94a3b8",
  },
  modeCardButtonText: {
    color: "white",
    fontWeight: "800",
    fontSize: 12,
    letterSpacing: 0.5,
  },
  adminContainer: {
    flex: 1,
    paddingHorizontal: 24,
    paddingBottom: 24,
    gap: 10,
  },
  adminHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  adminKeyRow: {
    maxHeight: 40,
  },
  adminKeyRowContent: {
    gap: 8,
    paddingRight: 8,
  },
  adminKeyChip: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 999,
    paddingHorizontal: 10,
    justifyContent: "center",
    height: 32,
    backgroundColor: "#f8fafc",
  },
  adminKeyChipActive: {
    backgroundColor: "#dbeafe",
    borderColor: "#2563eb",
  },
  adminKeyChipText: {
    fontSize: 12,
    color: "#334155",
    fontWeight: "700",
  },
  adminKeyChipTextActive: {
    color: "#1d4ed8",
  },
  adminLabel: {
    fontSize: 12,
    fontWeight: "900",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginTop: 4,
  },
  adminInput: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 10,
    backgroundColor: "white",
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    color: "#0f172a",
  },
  adminTextArea: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 12,
    backgroundColor: "white",
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 170,
    fontSize: 13,
    color: "#0f172a",
  },
  adminButtonsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
  },
  adminDeleteButton: {
    backgroundColor: "#dc2626",
  },
  adminStatusText: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: "700",
    color: "#475569",
  },
  storePriceText: {
    color: "#0f172a",
    fontSize: 14,
    fontWeight: "800",
  },
  storeBalanceText: {
    color: "#475569",
    fontSize: 12,
    fontWeight: "700",
  },
  timeTrialContainer: {
    flex: 1,
    paddingHorizontal: 24,
    paddingBottom: 16,
    gap: 14,
  },
  timeTrialDifficultyCard: {
    backgroundColor: "white",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 16,
    gap: 10,
  },
  timeTrialDurationsRow: {
    flexDirection: "row",
    gap: 10,
  },
  timeTrialDurationButton: {
    flex: 1,
    backgroundColor: "#dbeafe",
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  timeTrialDurationText: {
    color: "#1d4ed8",
    fontSize: 12,
    fontWeight: "900",
  },
  difficultySection: {},
  difficultyHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    gap: 12,
  },
  difficultyBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  difficultyBadgeText: {
    fontSize: 16,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: "#f1f5f9",
  },
  levelGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 6,
    marginBottom: 12,
  },
  levelButton: {
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    borderWidth: 2,
    padding: 8,
    width: 60,
    borderColor: "#f1f5f9",
  },
  levelButtonActive: {
    backgroundColor: "#2563eb",
    borderColor: "#2563eb",
  },
  levelButtonCompleted: {
    backgroundColor: "#dcfce7",
    borderColor: "#16a34a",
  },
  levelButtonCurrent: {
    shadowColor: "#16a34a",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
    elevation: 4,
  },
  levelButtonText: {
    fontSize: 18,
    fontWeight: "900",
    color: "#94a3b8",
  },
  levelButtonTextActive: {
    color: "white",
  },
  levelButtonTextCompleted: {
    color: "#166534",
  },
  gameContainer: {
    flex: 1,
  },
  gameHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 24,
  },
  root: {
    flex: 1,
    paddingTop: 36,
    backgroundColor: "white",
  },
  gameHeaderLeft: {
    flexDirection: "row",
    gap: 8,
    flex: 1,
  },
  gameIconButton: {
    width: 40,
    height: 40,
    backgroundColor: "#f1f5f9",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  levelIndicator: {
    alignItems: "center",
    flex: 1,
  },
  levelIndicatorLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  levelIndicatorValue: {
    fontSize: 20,
    fontWeight: "900",
    color: "#0f172a",
  },
  gameCoinBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fffbeb",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    flex: 1,
    justifyContent: "flex-end",
  },
  gameCoinText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#b45309",
    marginLeft: 6,
  },
  board: {
    width: GAME_WIDTH,
    height: GAME_HEIGHT,
    backgroundColor: "rgba(240, 240, 240, 1)",
    alignSelf: "center",
    marginBottom: 16,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: "#f1f5f9",
    overflow: "hidden",
  },
  boardSvg: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  nodeContainer: {
    position: "absolute",
    width: NODE_RADIUS * 2,
    height: NODE_RADIUS * 2,
    zIndex: 10,
  },
  nodeInner: {
    width: "100%",
    height: "100%",
    backgroundColor: "white",
    borderRadius: NODE_RADIUS,
    borderWidth: 4,
    borderColor: "#0f172a",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  nodeDot: {
    width: 4,
    height: 4,
    backgroundColor: "#0f172a",
    borderRadius: 2,
  },
  gameFooter: {
    alignItems: "center",
    paddingBottom: 32,
    paddingHorizontal: 32,
  },
  movesText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 8,
  },
  trialTimerText: {
    fontSize: 14,
    fontWeight: "900",
    color: "#1d4ed8",
    marginBottom: 6,
  },
  hintText: {
    fontSize: 10,
    color: "#94a3b8",
    textAlign: "center",
  },
  completeContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
  },
  trophyContainer: {
    width: 96,
    height: 96,
    backgroundColor: "#22c55e",
    borderRadius: 48,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
    shadowColor: "#22c55e",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 10,
  },
  completeTitle: {
    fontSize: 32,
    fontWeight: "900",
    color: "#0f172a",
    marginBottom: 8,
  },
  completeSubtitle: {
    fontSize: 16,
    color: "#94a3b8",
    marginBottom: 32,
  },
  rewardCard: {
    width: "100%",
    backgroundColor: "#f8fafc",
    borderRadius: 24,
    padding: 24,
    marginBottom: 32,
  },
  rewardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  rewardLabel: {
    fontSize: 16,
    color: "#64748b",
    fontWeight: "600",
  },
  rewardValue: {
    fontSize: 16,
    fontWeight: "900",
    color: "#0f172a",
  },
  rewardDivider: {
    height: 1,
    backgroundColor: "#e2e8f0",
    marginVertical: 16,
  },
  rewardTotalLabel: {
    fontSize: 18,
    fontWeight: "900",
    color: "#0f172a",
  },
  rewardTotalValueContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  rewardTotalValue: {
    fontSize: 24,
    fontWeight: "900",
    color: "#d97706",
  },
  completeButtonsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    gap: 16,
    width: "100%",
  },
  nextButton: {
    backgroundColor: "#2563eb",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 18,
    borderRadius: 20,
    shadowColor: "#2563eb",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 5,
    gap: 12,
  },
  nextButtonText: {
    color: "white",
    fontSize: 20,
    fontWeight: "800",
  },
  bannerAdContainer: {
    height: 50,
    backgroundColor: "#e2e8f0",
    justifyContent: "center",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#cbd5e1",
  },
  bannerAdPlaceholder: {
    fontSize: 12,
    color: "#94a3b8",
    fontWeight: "600",
  },
  popupAdOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.72)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  popupAdCard: {
    width: "100%",
    maxWidth: 320,
    backgroundColor: "white",
    borderRadius: 28,
    padding: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.18,
    shadowRadius: 28,
    elevation: 12,
  },
  popupAdTag: {
    fontSize: 11,
    fontWeight: "900",
    color: "#2563eb",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  popupAdTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: "#0f172a",
    textAlign: "center",
    marginBottom: 8,
  },
  popupAdBody: {
    fontSize: 14,
    color: "#64748b",
    textAlign: "center",
    marginBottom: 16,
    lineHeight: 20,
  },
  popupAdVideoFrame: {
    width: "100%",
    aspectRatio: 1.6,
    borderRadius: 20,
    backgroundColor: "#0f172a",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    overflow: "hidden",
  },
  popupAdPlayButton: {
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: "rgba(37, 99, 235, 0.92)",
    borderWidth: 5,
    borderColor: "rgba(255, 255, 255, 0.24)",
  },
  popupAdCountdown: {
    fontSize: 13,
    fontWeight: "800",
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
});

export {
  SCREEN_WIDTH,
  SCREEN_HEIGHT,
  GAME_WIDTH,
  GAME_HEIGHT,
  NODE_RADIUS,
  styles,
};
